services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: price_etl
    ports:
      - "5432:5432"
    volumes:
      - pgdata_price_etl:/var/lib/postgresql/data
volumes:
  pgdata_price_etl:
